name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - lib/**
      - .github/workflows/**
      - native/**
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Rust & Prepare Complie
        run: |
          rustup update stable
          cargo install rinf
          rinf message
          dart fix --apply
      - name: Build
        run: flutter build windows --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: build/windows/x64/runner/Release/*



